import { type Application as PixiApplication } from 'pixi.js';
import { type ForwardRefRenderFunction } from 'react';
import { type ApplicationProps } from '../typedefs/ApplicationProps';
/** Creates a React root and renders a Pixi application. */
export declare const ApplicationFunction: ForwardRefRenderFunction<PixiApplication, ApplicationProps>;
export declare const Application: import("react").ForwardRefExoticComponent<import("../typedefs/ApplicationProps").BaseApplicationProps & Partial<{
    preference?: ("webgl" | "webgpu") | undefined;
    webgpu?: Partial<import("pixi.js").WebGPUOptions> | undefined;
    webgl?: Partial<import("pixi.js").WebGLOptions> | undefined;
    skipExtensionImports?: boolean | undefined;
    manageImports?: boolean | undefined;
    backgroundColor?: import("pixi.js").ColorSource | undefined;
    background?: import("pixi.js").ColorSource | undefined;
    backgroundAlpha?: number | undefined;
    clearBeforeRender?: boolean | undefined;
    hello?: boolean | undefined;
    width?: number | undefined;
    height?: number | undefined;
    canvas?: import("pixi.js").ICanvas | undefined;
    view?: import("pixi.js").ICanvas | undefined;
    autoDensity?: boolean | undefined;
    resolution?: number | undefined;
    antialias?: boolean | undefined;
    depth?: boolean | undefined;
    multiView?: boolean | undefined;
    textureGCActive?: boolean | undefined;
    textureGCAMaxIdle?: number | undefined;
    textureGCCheckCountMax?: number | undefined;
    eventMode?: import("pixi.js").EventMode | undefined;
    eventFeatures?: import("pixi.js").EventSystemOptions["eventFeatures"];
    failIfMajorPerformanceCaveat?: boolean | undefined;
    roundPixels?: boolean | undefined;
    bezierSmoothness?: number | undefined;
    context?: WebGL2RenderingContext | null | undefined;
    powerPreference?: import("pixi.js").GpuPowerPreference | undefined;
    premultipliedAlpha?: boolean | undefined;
    preserveDrawingBuffer?: boolean | undefined;
    preferWebGLVersion?: (1 | 2) | undefined;
    useBackBuffer?: boolean | undefined;
    forceFallbackAdapter?: boolean | undefined;
    resizeTo?: HTMLElement | Window | import("react").RefObject<HTMLElement> | undefined;
    autoStart?: boolean | undefined;
    sharedTicker?: boolean | undefined;
}> & import("react").RefAttributes<PixiApplication<import("pixi.js").Renderer>>>;
